package ui.template; /**
 * A basic implementation of the JDialog class.
 **/

import ui.plugin.AddPersonalAccountDialogPlugin;

import javax.swing.*;
import java.awt.*;
import java.util.Optional;

public final class AddPersonalAccountDialogTemplate extends JDialog {

    private MainFrameTemplate parentframe;

    public AddPersonalAccountDialogTemplate(MainFrameTemplate parent, AddPersonalAccountDialogPlugin dialogPlugin) {
        super(parent);
        parentframe = parent;

        // This code is automatically generated by Visual Cafe when you add
        // components to the visual environment. It instantiates and initializes
        // the components. To modify the code, only use code syntax that matches
        // what Visual Cafe can generate, or Visual Cafe may be unable to back
        // parses your Java file into its visual environment.
        //{{ INIT_CONTROLS
        setTitle(dialogPlugin.getDialogName());
        setModal(true);
        getContentPane().setLayout(null);
        setSize(283, 303);
        setVisible(false);

        Optional.ofNullable(dialogPlugin.getTopPanel()).ifPresent(getContentPane()::add);

        JLabel1.setText("Name");
        getContentPane().add(JLabel1);
        JLabel1.setForeground(Color.black);
        JLabel1.setBounds(12, 84, 48, 24);
        JLabel2.setText("Street");
        getContentPane().add(JLabel2);
        JLabel2.setForeground(Color.black);
        JLabel2.setBounds(12, 108, 48, 24);
        JLabel3.setText("City");
        getContentPane().add(JLabel3);
        JLabel3.setForeground(Color.black);
        JLabel3.setBounds(12, 132, 48, 24);
        JLabel4.setText("State");
        getContentPane().add(JLabel4);
        JLabel4.setForeground(Color.black);
        JLabel4.setBounds(12, 156, 48, 24);
        JLabel5.setText("Zip");
        getContentPane().add(JLabel5);
        JLabel5.setForeground(Color.black);
        JLabel5.setBounds(12, 180, 48, 24);
        JLabel6.setText("Birthdate");
        getContentPane().add(JLabel6);
        JLabel6.setForeground(Color.black);
        JLabel6.setBounds(12, 204, 96, 24);
        JLabel7.setText("Email");
        getContentPane().add(JLabel7);
        JLabel7.setForeground(Color.black);
        JLabel7.setBounds(12, 228, 48, 24);
        getContentPane().add(JTextField_NAME);
        JTextField_NAME.setBounds(84, 84, 156, 20);
        getContentPane().add(JTextField_CT);
        JTextField_CT.setBounds(84, 132, 156, 20);
        getContentPane().add(JTextField_ST);
        JTextField_ST.setBounds(84, 156, 156, 20);
        getContentPane().add(JTextField_STR);
        JTextField_STR.setBounds(84, 108, 156, 20);
        getContentPane().add(JTextField_ZIP);
        JTextField_ZIP.setBounds(84, 180, 156, 20);

        Optional.ofNullable(dialogPlugin.getBottomPanel()).ifPresent(getContentPane()::add);

        JButton_OK.setText("OK");
        JButton_OK.setActionCommand("OK");
        getContentPane().add(JButton_OK);
        JButton_OK.setBounds(48, 264, 84, 24);
        JButton_Cancel.setText("Cancel");
        JButton_Cancel.setActionCommand("Cancel");
        getContentPane().add(JButton_Cancel);
        JButton_Cancel.setBounds(156, 264, 84, 24);
        getContentPane().add(JTextField_ACNR);
        JTextField_ACNR.setBounds(84, 60, 156, 20);
        JLabel8.setText("Acc Nr");
        getContentPane().add(JLabel8);
        JLabel8.setForeground(Color.black);
        JLabel8.setBounds(12, 60, 48, 24);
        //}}

        //{{REGISTER_LISTENERS
        SymAction lSymAction = new SymAction();
        JButton_OK.addActionListener(lSymAction);
        JButton_Cancel.addActionListener(lSymAction);
        //}}
    }


    //{{DECLARE_CONTROLS
    JLabel JLabel1 = new JLabel();
    JLabel JLabel2 = new JLabel();
    JLabel JLabel3 = new JLabel();
    JLabel JLabel4 = new JLabel();
    JLabel JLabel5 = new JLabel();
    JLabel JLabel6 = new JLabel();
    JLabel JLabel7 = new JLabel();
    JTextField JTextField_NAME = new JTextField();
    JTextField JTextField_CT = new JTextField();
    JTextField JTextField_ST = new JTextField();
    JTextField JTextField_STR = new JTextField();
    JTextField JTextField_ZIP = new JTextField();
    JButton JButton_OK = new JButton();
    JButton JButton_Cancel = new JButton();
    JTextField JTextField_ACNR = new JTextField();
    JLabel JLabel8 = new JLabel();
    //}}

    class SymAction implements java.awt.event.ActionListener {
        public void actionPerformed(java.awt.event.ActionEvent event) {
            Object object = event.getSource();
            if (object == JButton_OK)
                JButtonOK_actionPerformed(event);
            else if (object == JButton_Cancel)
                JButtonCalcel_actionPerformed(event);
        }
    }

    void JButtonOK_actionPerformed(java.awt.event.ActionEvent event) {
        parentframe.accountnr = JTextField_ACNR.getText();
        parentframe.clientName = JTextField_NAME.getText();
        parentframe.street = JTextField_STR.getText();
        parentframe.city = JTextField_CT.getText();
        parentframe.zip = JTextField_ZIP.getText();
//        parentframe.state = JTextField_ST.getText();
//        if (JRadioButton_Chk.isSelected())
//            parentframe.accountType = "Ch";
//        else
//            parentframe.accountType = "S";
        parentframe.newaccount = true;
        dispose();
    }

    void JButtonCalcel_actionPerformed(java.awt.event.ActionEvent event) {
        //make this frame invisible if Cancel button is clicked
        dispose();
    }
}